### ISSUE TITLE
How does this one work?

### ISSUE THREAD

**Issue by BBassi** [epi2me-labs/jupyterlab-code-cell-collapser#1]

**Comment by cjw85** [comment]
If a codecell has a comment on the first line, an additional grey bar is displayed in the left-hand margin.
![image](https://user-images.githubusercontent.com/3592009/95589069-26311b00-0a3c-11eb-93a5-8bfa735c48ff.png)

Clicking that grey button collapses the cell down to the comment:
![image](https://user-images.githubusercontent.com/3592009/95589123-3943eb00-0a3c-11eb-966f-f6921aa8d52b.png)
allowing the code to be hidden but maintaining a visual hint as to the cells contents.

This is an alternative to the standard blue collapse button which results in:
![image](https://user-images.githubusercontent.com/3592009/95589242-5f698b00-0a3c-11eb-9830-259831fa527c.png)

The extension was developed because we found that with this default behaviour code cells can get lost and are hard to find.

**Comment by BBassi** [comment]
Nice extension! Plan to use it. I have installed it however when closing a notebook I now get these errors in browser console.
![Screenshot 2020-10-25 at 19 43 28](https://user-images.githubusercontent.com/25634627/97117291-93aaa000-16fa-11eb-9c35-3e27d8a74812.png)

**Comment by Karhide** [comment]
Thanks for pointing this out. A new version has been pushed which addresses this issue. Let us know if it persists!

**Comment by BBassi** [comment]
![image (10)](https://user-images.githubusercontent.com/25634627/97428521-fde75e80-190d-11eb-8d8f-b03ff2e779bb.png)

This error was thrown when opening a notebook - think its due to the current cell being "null" - we added this check locally - it seems to fix it

index.ts:64:69

    nbTrack.activeCellChanged.connect(() => {
          const cell: Cell = notebook.activeCell;
          if (cell !== null) {
              addCodeCellCollapser(cell, notebookCellCollapsers);
          }
        });

**Comment by Karhide** [comment]
Thanks, much appreciated. Your fix worked for me too, and has been pushed to NPM.

**Comment by sickerin** [comment]
Thank god this exists :))). I was trying to find something like this for jupyterlab for a while now or make it myself. Have you considered contributing this to the Jupyter lab repo so that it's inbuilt, like a setting you users can choose, to enable this or not.

**Comment by cjw85** [comment]
@sickerin

The functionality of this extension has been often requested for Jupyterlab in issues. There are however good
