### ISSUE TITLE
JLAB3

### ISSUE THREAD

**Issue by BBassi** [epi2me-labs/jupyterlab-code-cell-collapser#2]
Any plans to migrate to JLAB3?

**Comment by cjw85** [comment]
We are reviewing the use of JupyterLab 3, the extension should be easy to migrate. If it is @Karhide will be able to make it happen fairly quickly, if more work is required it might not be a priority for us to update (we're not using JL3 ourselves yet because key extensions that we use do not support it).

**Comment by Karhide** [comment]
Migration to Jupyterlab 3 complete, please let us know if there any issues.
